import Foundation

/// Word-level alignment client for the local whisper.cpp server.
///
/// Sends a WAV blob (already generated by TTS) to the local whisper-server
/// running on 127.0.0.1:8724 and parses the `verbose_json` response into
/// a flat array of `(word, start, end)` tuples that the TTSDialog can use
/// to karaoke-highlight words in sync with `AVAudioPlayer.currentTime`.
enum WordAligner {

    struct Word: Codable {
        let text: String
        let start: Double
        let end: Double
    }

    static let baseURL = ConfigManager.sttBaseURL  // http://127.0.0.1:8724

    /// POSTs `wavData` to whisper-server `/inference` with verbose_json +
    /// word-level segmentation flags. Returns one `Word` per spoken word.
    /// Throws on network / HTTP / decode error.
    static func align(wavData: Data) async throws -> [Word] {
        let boundary = UUID().uuidString
        var request = URLRequest(url: URL(string: "\(baseURL)/inference")!)
        request.httpMethod = "POST"
        request.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = 60

        var body = Data()
        func append(_ str: String) { body.append(str.data(using: .utf8)!) }

        append("--\(boundary)\r\n")
        append("Content-Disposition: form-data; name=\"file\"; filename=\"audio.wav\"\r\n")
        append("Content-Type: audio/wav\r\n\r\n")
        body.append(wavData)
        append("\r\n")

        let fields: [(String, String)] = [
            ("response_format", "verbose_json"),
            ("temperature", "0.0"),
            ("max_len", "1"),
            ("split_on_word", "true"),
            ("word_thold", "0.01"),
            ("language", "en"),
        ]
        for (k, v) in fields {
            append("--\(boundary)\r\n")
            append("Content-Disposition: form-data; name=\"\(k)\"\r\n\r\n")
            append("\(v)\r\n")
        }
        append("--\(boundary)--\r\n")
        request.httpBody = body

        let (data, response) = try await URLSession.shared.data(for: request)

        if let http = response as? HTTPURLResponse, http.statusCode != 200 {
            let snippet = String(data: data, encoding: .utf8).map { String($0.prefix(200)) } ?? "<non-utf8>"
            Log.error("[ALIGN] HTTP \(http.statusCode): \(snippet)")
            throw NSError(domain: "WordAligner", code: http.statusCode,
                          userInfo: [NSLocalizedDescriptionKey: "whisper-server \(http.statusCode)"])
        }

        return parseVerboseJSON(data)
    }

    /// Parse whisper.cpp verbose_json: `{"segments":[{"text":" word","start":0.00,"end":0.36}, ...]}`
    /// With `max_len=1 split_on_word=true`, each segment corresponds to one word.
    private static func parseVerboseJSON(_ data: Data) -> [Word] {
        guard let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let segments = obj["segments"] as? [[String: Any]] else {
            Log.error("[ALIGN] failed to parse verbose_json")
            return []
        }

        var words: [Word] = []
        words.reserveCapacity(segments.count)
        for seg in segments {
            guard let rawText = seg["text"] as? String else { continue }
            let text = rawText.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }
            let start = (seg["start"] as? Double) ?? 0
            let end = (seg["end"] as? Double) ?? start
            words.append(Word(text: text, start: start, end: end))
        }
        return words
    }
}
